### ISSUE TITLE
Paper should have and belong to many authors

### ISSUE THREAD

**Issue by swt2public** [swt2-intro-exercise/rails-exercise-20-felixauringer#13]
### Scenario
Given a paper
Then it should have an empty list of authors

### Hints
A paper can have many authors and an author can write many papers.
This relationship is indicated in Rails by annotating both models (i.e. the `Author` and `Paper`) with a [`has_and_belongs_to_many`](https://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association) association.

To store this n:m relation, create a new database table in a migration: [guide](https://guides.rubyonrails.org/active_record_migrations.html#creating-a-join-table).
There is a [generator](https://guides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration) which can produce join tables if 'JoinTable' is part of the name:

`rails generate migration CreateJoinTableAuthorPaper author paper`

To test if such a relation exists, you can test whether a paper has an empty list of authors.

*Reminder:* Migrations are stored in `db/migrate` and are applied with the `rails db:migrate` command.

### Error
> Got NoMethodError: undefined method `authors' for #<Paper:0x0000000001ac4530>

*38/44 exercise tests have passed*

**Comment by felixauringer** [comment]
Fixed in 19df66f3b6b0a80e49e1b855a3ef6ca2f6adc350
